_BASE_: "COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x.yaml"

DATALOADER:
  NUM_WORKERS: 8
  FILTER_EMPTY_ANNOTATIONS: False

MODEL:
  ROI_HEADS:
    NUM_CLASSES: 1
    NMS_THRESH_TEST: 0.6 # Could be overloaded ```python train.py MODEL.ROI_HEADS.NMS_THRESH_TEST=0.7```
    SCORE_THRESH_TEST: 0.7

  RETINANET:
    NUM_CLASSES: 1

DATASETS:
  TRAIN: ("uchastok_train", )
  TEST: ("uchastok_eval", )

SOLVER:
  STEPS: [ ]

TEST:
  EVAL_PERIOD: 1000

INPUT:
  FORMAT: "RGB"